apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
      # annotations:
      #   "openservicemesh.io/sidecar-injection": "enabled"
    spec:
      serviceAccountName: movies-api-service-account
      terminationGracePeriodSeconds: 5
      containers:
      - name: api
        image: hjgraca/movies-api:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        # readinessProbe:
        #   initialDelaySeconds: 20
        #   periodSeconds: 15
        #   httpGet:
        #     path: /health/ready
        #     port: 80
        # livenessProbe:
        #   initialDelaySeconds: 20
        #   periodSeconds: 15
        #   httpGet:
        #     path: /health/live
        #     port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: movies-api
spec:
  selector:
    app: movies-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: movies-api-port