apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-service-account
      terminationGracePeriodSeconds: 5
      containers:
      - name: api
        image: hjgraca/frontend:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MoviesApiUri
          value: "http://movies-api"
        - name: RecommendationApiUri
          value: "http://recommendation-api"
        - name: BasketApiUri
          value: "http://basket-api"
        - name: CheckoutApiUri
          value: "http://checkout-api"
        - name: AdsApiUri
          value: "http://ads-api"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          httpGet:
            path: /healthx
            port: 3000
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
